name: Build Image

on:
  workflow_call:
    inputs:
      file:
        required: false
        default: Dockerfile
        type: string
      context:
        required: false
        type: string
        default: .
      tags:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    name: Build Image

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:


          context: ${{ inputs.context }}
          tags: ${{ inputs.tags }}
          push: true
          #target: production
          file: ${{ inputs.file }}

      - name: Image digest
        run: |
          echo ${{ steps.docker_build.outputs.imageid }}
          echo ${{ steps.docker_build.outputs.digest }}
          echo ${{ steps.docker_build.outputs.metadata }}
